swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Contacts API"
host: "localhost:8080"
basePath: "/api/v1"
tags:
- name: "contact"
  description: "Contacts"
- name: "skill"
  description: "Contact skills"
schemes:
#- "https"
- "http"
paths:
  /contacts:
    get:
      tags:
      - "contact"
      summary: "List contacts"
      description: ""
      operationId: "listContacts"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
    post:
      tags:
      - "contact"
      summary: "Add a contact"
      description: ""
      operationId: "addContact"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contact object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Contact"
      responses:
        405:
          description: "Invalid input"
      # security:
      # - contact_auth:
      #   - "write"
      #   - "read"
    put:
      tags:
      - "contact"
      summary: "Update an existing contact"
      description: ""
      operationId: "updateContact"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contact object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Contact"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Contact not found"
        405:
          description: "Validation exception"
      # security:
      # - contact_auth:
      #   - "write"
      #   - "read"
  /contacts/{contactId}:
    get:
      tags:
      - "contact"
      summary: "Find contact by ID"
      description: "Returns a single contact"
      operationId: "getContactById"
      produces:
      - "application/json"
      parameters:
      - name: "contactId"
        in: "path"
        description: "ID of contact to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Contact"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Contact not found"
      # security:
      # - api_key: []
    delete:
      tags:
      - "contact"
      summary: "Deletes a contact"
      description: ""
      operationId: "deleteContact"
      produces:
      - "application/json"
      parameters:
      # - name: "api_key"
      #   in: "header"
      #   required: false
      #   type: "string"
      - name: "contactId"
        in: "path"
        description: "Contact id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Contact not found"
      # security:
      # - contact_auth:
      #   - "write"
      #   - "read"
  /contacts/{contactId}/addSkill:
    post:
      tags:
      - "contact"
      summary: "Adds a skill to a contact"
      description: ""
      operationId: "addContactSkill"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "contactId"
        in: "path"
        description: "ID of contact to update"
        required: true
        type: "integer"
        format: "int64"
      - name: "skill"
        in: "body"
        description: "ID of skill to add"
        required: true
        schema:
          $ref: "#/definitions/ContactSkill"
      responses:
        200:
          description: "Skill added to contact"
          # schema:
          #   $ref: "#/definitions/ModelApiResponse"
      # security:
      # - contact_auth:
      #   - "write"
      #   - "read"
  /skills:
    get:
      tags:
      - "skill"
      summary: "List skills"
      description: ""
      operationId: "listSkills"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: '#/definitions/Skill'
    post:
      tags:
      - "skill"
      summary: "Add a skill"
      description: ""
      operationId: "addSkill"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Skill object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Skill"
      responses:
        405:
          description: "Invalid input"
      # security:
      # - contact_auth:
      #   - "write"
      #   - "read"
    put:
      tags:
      - "skill"
      summary: "Update an existing skill"
      description: ""
      operationId: "updateSkill"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Skill that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Skill"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Skill not found"
        405:
          description: "Validation exception"
      # security:
      # - contact_auth:
      #   - "write"
      #   - "read"
  /skill/{skillId}:
    get:
      tags:
      - "skill"
      summary: "Find skill by ID"
      description: "Returns a single skill"
      operationId: "getSkillById"
      produces:
      - "application/json"
      parameters:
      - name: "skillId"
        in: "path"
        description: "ID of skill to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Contact"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Contact not found"
      # security:
      # - api_key: []
    delete:
      tags:
      - "skill"
      summary: "Deletes a skill"
      description: ""
      operationId: "deleteSkill"
      produces:
      - "application/json"
      parameters:
      # - name: "api_key"
      #   in: "header"
      #   required: false
      #   type: "string"
      - name: "skillId"
        in: "path"
        description: "Skill ID to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Skill not found"
      # security:
      # - contact_auth:
      #   - "write"
      #   - "read"
# securityDefinitions:
#   contact_auth:
#     type: "oauth2"
#     authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#     flow: "implicit"
#     scopes:
#       write: "modify pets in your account"
#       read: "read your pets"
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"
definitions:
  Contact:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
      fullName:
        type: "string"
      address:
        type: "string"
      email:
        type: "string"
      mobilePhoneNumber:
        type: "string"
      skills:
        type: array
        items:
          $ref: '#/definitions/ContactSkill'
  ContactSkill:
    type: "object"
    properties:
      skill:
        $ref: '#/definitions/Skill'
      level:
        type: "string"
        enum: 
        - "very good"
        - "good"
        - "average"
        - "poor"
  Skill:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  # ModelApiResponse:
  #   type: "object"
  #   properties:
  #     code:
  #       type: "integer"
  #       format: "int32"
  #     type:
  #       type: "string"
  #     message:
  #       type: "string"