version: '3.1'
services :
    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: pa55w0rd
            POSTGRES_DB: contacts
    admin:
        image: adminer
        restart: always
        depends_on: 
        - db
        ports:
        - 8081:8080
